#!/bin/bash
# docker run -it -v /media/jmmease/SSD1/chromium_build/repos/:/repos  jonmmease/chromium-builder:0.5 /repos/build_headless
if [ $# -eq 0 ]; then
    echo "No architecture provided"
    exit 1
fi

export KALEIDO_ARCH=$1


cd /repos/src

# Make output directory
mkdir -p out/Kaleido_linux_$KALEIDO_ARCH

# Write out/Kaleido_linux_$KALEIDO_ARCH/args.gn
cp /repos/linux_scripts/args_$KALEIDO_ARCH.gn out/Kaleido_linux_$KALEIDO_ARCH/args.gn
gn gen out/Kaleido_linux_$KALEIDO_ARCH

# perform_kaleido_build expect to be run from src directory
/repos/linux_scripts/perform_kaleido_build
