#!/bin/bash
# docker run -it -v /media/jmmease/SSD1/chromium_build/repos/:/repos  jonmmease/chromium-builder:0.5 /repos/build_headless

cd /repos/src

# Make output directory
mkdir -p out/Kaleido_linux

# Write out/Kaleido_linux/args.gn
cp /repos/linux_scripts/args.gn out/Kaleido_linux/args.gn

# 1) Reset headless/BUILD.gn
git checkout HEAD -- headless/BUILD.gn

# 2) Append kaleido section to headless build file (src/headless/BUILD.gn)
echo "
executable(\"kaleido\") {
  sources = [ \"app/kaleido.cc\" ]

  deps = [
    \":headless_shell_lib\",
    \"//skia\",  # we need this to override font render hinting in headless build
  ]
}" >> headless/BUILD.gn

# perform_kaleido_build expect to be run from src directory
/repos/linux_scripts/perform_kaleido_build
