#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No architecture provided"
    exit 1
fi
export KALEIDO_ARCH=$1

# full path to linux_scripots/ directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# cd to the top-level project directory
cd $DIR/../..

# Update version based on git tags
python ./repos/version/build_pep440_version.py

# Copy README and LICENSE to kaleido directory so it's available in the docker container
cp ./README.md ./repos/kaleido/
cp ./LICENSE.txt ./repos/kaleido/

# Perform build using docker
docker run -it -v `pwd`/repos/:/repos  jonmmease/chromium-builder:0.8 /repos/linux_scripts/build_kaleido_docker $KALEIDO_ARCH
