#!/bin/bash
# docker run -it -v /media/jmmease/SSD1/chromium_build/repos/:/repos  jonmmease/chromium-builder:0.5 /repos/build_headless

cd /repos/src

# Run vs_toolchain.py to create the fuse mount at
# src/third_party/depot_tools/win_toolchain/vs_files
vpython build/vs_toolchain.py update --force

# Make output directory
mkdir -p out/Kaleido_win

# Write out/Kaleido_win/args.gn
echo "
# Copied windows compatible options from //build/args/headless.gn
# Embed resource.pak into binary to simplify deployment.
#headless_use_embedded_resources = true

# Use embedded data instead external files for headless in order
# to simplify deployment.
v8_use_external_startup_data = false

enable_nacl = false
enable_remoting = false

# cross compile
target_os=\"win\"
target_cpu=\"x64\"

# Debug / symbols
symbol_level=0
blink_symbol_level=0
is_debug=false
is_component_build=false
" > out/Kaleido_win/args.gn

# 1) Reset headless/BUILD.gn
git checkout HEAD -- headless/BUILD.gn

# 2) Append kaleido section to headless build file (src/headless/BUILD.gn)
echo "
executable(\"kaleido\") {
  sources = [ \"app/kaleido.cc\" ]

  deps = [
    \":headless_shell_lib\",
    \"//skia\",  # we need this to override font render hinting in headless build
  ]
}" >> headless/BUILD.gn

# 3) Copy kaleido/kaleido.cc to src/headless/app/kaleido.cc
rm -rf headless/app/plugins
cp -r ../kaleido/cc/* headless/app/

# 4) Perform build, result will be out/Kaleido_win/kaleido
gn gen out/Kaleido_win
ninja -C out/Kaleido_win -j 20 kaleido

# 5) Copy build files
mkdir -p ../build/kaleido_win/
rm -r ../build/kaleido_win/*
cp out/Kaleido_win/kaleido.exe ../build/kaleido_win/
cp -r out/Kaleido_win/swiftshader/ ../build/kaleido_win/

# Copy icudtl.dat
cp ./out/Kaleido_win/icudtl.dat ../build/kaleido_win/

# Copy javascript
pushd ../kaleido/js/
mkdir -p build/
npm install
npm run clean
npm run build
popd

mkdir -p ../build/kaleido_win/js/
cp ../kaleido/js/build/*.js ../build/kaleido_win/js/
