#!/bin/bash
# docker run -it -v /media/jmmease/SSD1/chromium_build/repos/:/repos  jonmmease/chromium-builder:0.5 /repos/build_headless
if [ $# -eq 0 ]; then
    echo "No architecture provided"
    exit 1
fi

export KALEIDO_ARCH=$1


cd /repos/src

if [ $KALEIDO_ARCH == arm64 ]; then
    echo "Installing sysroot"
    python ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
fi

# Make output directory
mkdir -p out/Kaleido_linux_$KALEIDO_ARCH

# Write out/Kaleido_linux_$KALEIDO_ARCH/args.gn
cp /repos/linux_scripts/args_$KALEIDO_ARCH.gn out/Kaleido_linux_$KALEIDO_ARCH/args.gn
gn gen out/Kaleido_linux_$KALEIDO_ARCH

# 1) Reset headless/BUILD.gn
git checkout HEAD -- headless/BUILD.gn

# 2) Append kaleido section to headless build file (src/headless/BUILD.gn)
echo "
executable(\"kaleido\") {
  sources = [ \"app/kaleido.cc\" ]

  deps = [
    \":headless_shell_lib\",
    \"//skia\",  # we need this to override font render hinting in headless build
  ]
}" >> headless/BUILD.gn

# perform_kaleido_build expect to be run from src directory
/repos/linux_scripts/perform_kaleido_build
