#!/bin/bash
CHROMIUM_TAG="83.0.4103.61"

cd /repos/src
git reset --hard
git checkout tags/$CHROMIUM_TAG
gclient sync -D --force --reset
gclient runhooks

# Build credits
python /repos/src/tools/licenses.py credits > /repos/CREDITS.html
