#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No architecture provided"
    exit 1
fi
export KALEIDO_ARCH=$1

# perform_kaleido_build expect to be run from src directory
cd /src
/repos/linux_scripts/perform_kaleido_build