#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No architecture provided"
    exit 1
fi

export KALEIDO_ARCH=$1

# Don't autoupdate depottools version
export DEPOT_TOOLS_UPDATE=0

# full path to mac_scripts/ directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# cd to repos directory
cd $DIR/..

# Add depot_tools directory to PATH
export PATH="$PATH:`pwd`/depot_tools"

# Make output directory
mkdir -p ./src/out/Kaleido_mac_$KALEIDO_ARCH/

# Write out/Kaleido_mac_$KALEIDO_ARCH/args.gn
cp ./mac_scripts/args_$KALEIDO_ARCH.gn ./src/out/Kaleido_mac_$KALEIDO_ARCH/args.gn

# cd to repos/src
cd src

# 4) Perform build, result will be out/Kaleido_mac_$KALEIDO_ARCH/kaleido
gn gen out/Kaleido_mac_$KALEIDO_ARCH
ninja -C out/Kaleido_mac_$KALEIDO_ARCH -j 8 gl_blink
