#!/bin/bash

# full path to mac_scripts/ directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# cd to repos directory
cd $DIR/..

# Add depot_tools directory to PATH
export PATH="$PATH:`pwd`/depot_tools"

# cd to repos/src
cd src

# Make output directory
mkdir -p out/Headless_mac

# Write out/Headless_mac/args.gn
echo "
# Copied windows compatible options from //build/args/headless.gn
# Embed resource.pak into binary to simplify deployment.
headless_use_embedded_resources = true

# Use embedded data instead external files for headless in order
# to simplify deployment.
v8_use_external_startup_data = false

enable_nacl = false
enable_remoting = false

# Debug / symbols
symbol_level=0
blink_symbol_level=0
is_debug=false
is_component_build=false
" > out/Headless_mac/args.gn


# 1) Reset headless/BUILD.gn
git checkout HEAD -- headless/BUILD.gn

# 2) Append orca_next section to headless build file (src/headless/BUILD.gn)
echo "
executable(\"orca_next\") {
  sources = [ \"app/orca_next.cc\" ]

  deps = [
    \":headless_shell_lib\",
    \"//skia\",  # we need this to override font render hinting in headless build
  ]
}" >> headless/BUILD.gn

# 3) Copy orca_next/orca_next.cc to src/headless/app/orca_next.cc
rm -rf headless/app/plugins
cp -r ../orca_next/cc/* headless/app/

# 4) Perform build, result will be out/Headless_mac/orca_next
gn gen out/Headless_mac
ninja -C out/Headless_mac -j 8 orca_next

# 5) Copy build files
mkdir -p ../build/orca_next_mac/
rm -r ../build/orca_next_mac/*
mkdir -p ../build/orca_next_mac/bin
cp out/Headless_mac/orca_next ../build/orca_next_mac/bin
cp -r out/Headless_mac/swiftshader/ ../build/orca_next_mac/bin

# launch script
echo "#!/bin/bash
DIR=\"\$( cd \"\$( dirname \"\${BASH_SOURCE[0]}\" )\" >/dev/null 2>&1 && pwd )\"

cd \$DIR
./bin/orca_next --no-sandbox --disable-gpu --allow-file-access-from-files --disable-breakpad \$@
" > ../build/orca_next_mac/orca_next
chmod +x ../build/orca_next_mac/orca_next

# Copy javascript
pushd ../orca_next/js/
mkdir -p build/
npm install
./node_modules/browserify/bin/cmd.js --s orca_next src/component/plotly-graph/index.js > build/bundle.js
popd

mkdir -p ../build/orca_next_mac/js/
cp ../orca_next/js/build/bundle.js ../build/orca_next_mac/js/
