#!/bin/bash

# Commits
DEPOT_TOOLS_COMMIT="" # Can't set a version for Windows, maybe we can for make depending on TODO below, probably won't
CHROMIUM_TAG="124.0.6367.60"
export DEPOT_TOOLS_UPDATE=0 # TODO: Don't know if this will work on Mac

# full path to mac_scripts/ directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# cd to repos directory
cd $DIR/..

# Get depot_tools
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
cd depot_tools

# Add cloned depot_tools directory to PATH
export PATH="$PATH:`pwd`"

# Reset to proper commit
git reset --hard $DEPOT_TOOLS_COMMIT
git clean -ffd

# Move back to repos directory
cd ../src

gclient sync -D --force --reset --no-history --jobs=3 --revision=$CHROMIUM_TAG 

# Write out credits file
cd ..
python ./src/tools/licenses.py credits > ./CREDITS.html
